### ISSUE TITLE
Cant add team in teams preview

### ISSUE THREAD

**Issue by nyet-ty** [taskany-inc/crew#315]
<img width="1074" alt="image" src="https://github.com/taskany-inc/crew/assets/61706821/894d9459-815e-44b4-9536-75e54db10f73">
<img width="974" alt="image" src="https://github.com/taskany-inc/crew/assets/61706821/f9084ac0-4b81-4d6c-8597-4f2cfe8139d7">

**Comment by Katrin-kudryash** [comment]
You can add a group. You can write name of group and choose from combobox
