### ISSUE TITLE
Hiring stream id in vacancy model should be Int

### ISSUE THREAD

**Issue by nyet-ty** [taskany-inc/crew#600]
Right now it is string, that conflicts with hiring stream id in hire

https://github.com/taskany-inc/crew/blob/cd00e1e72a14958df1663e6fdeebbf39e67729a3/prisma/schema.prisma#L261C22-L262C1

https://github.com/taskany-inc/crew/blob/c19b97fa560644c802eb414fa8f14d325828601b/src/modules/vacancyMethods.ts#L59

**Comment by 9teen90nine** [comment]
It should probably be fixed in hire because string is a wider type
