### ISSUE TITLE
Group administrator can't edit group

### ISSUE THREAD

**Issue by asabotovich** [taskany-inc/crew#833]
<img width="910" alt="Снимок экрана 2024-06-04 в 13 27 26" src="https://github.com/taskany-inc/crew/assets/9020793/3ac92a8f-2af3-442d-9528-92eb6ad929fa">

It's require additionally have a role with `editAdministratedGroupTree` flag

**Comment by 9teen90nine** [comment]
Deprecate -editAdministratedGroupTree- scope
